pre-release-commit-message = "Release ({{crate_name}}) : {{version}}"
sign-commit = true
sign-tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/Microsoft/snocat/compare/{{tag_name}}...HEAD", exactly=1},
]
# removed in https://github.com/crate-ci/cargo-release/pull/300/files; saved for per-project reference
# exclude-paths = ["docs/**", "README.md", "tests/**", ".scripts", ".github", ".*", "certs", "target"]
