[package]
name = "snocat"
description = "Streaming Network Overlay Connection Arbitration Tunnel"
version = "0.2.0-alpha.10"
authors = ["Microsoft Corporation", "Zoey <Dessix@Dessix.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/snocat"
categories = ["network-programming"]
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "*.md"]

[dependencies]
anyhow = "~1.0.42"
downcast-rs = "^1.2.0"
futures = "^0.3.15"
futures-io = "^0.3.15"
gen-z = "~0.1.0"
lazy_static = "1.4.0"
log = "~0.4.13"
quinn = "~0.7.2"
serde = { version = "~1.0.126", features=["derive"] }
serde_json = "~1.0.64"
thiserror = "^1.0.26"
tracing = "~0.1.22"
tracing-futures = "~0.2.4"
tracing-subscriber = "~0.2.19"
tokio = { version = "^1.8.1", features=["net", "io-util", "signal", "sync", "time", "macros", "rt-multi-thread"] }
tokio-stream = { version = "^0.1.7", features=["net", "io-util", "sync"] }
tokio-util = { version = "^0.6.7", features=["default", "io", "time"] }

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["core"]
core = []

full = ["core"]
