[package]
name = "snocat"
description = "Streaming Network Overlay Connection Arbitration Tunnel"
version = "0.3.0-alpha.2"
authors = ["Microsoft Corporation", "Zoey <Dessix@Dessix.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/microsoft/snocat"
categories = ["network-programming"]
include = ["src/**/*", "build.rs", "Cargo.toml", "LICENSE*", "*.md"]

[dependencies]
anyhow = "~1.0.43"
downcast-rs = "^1.2.0"
futures = "^0.3.17"
futures-io = "^0.3.17"
gen-z = "~0.1.0"
log = "~0.4.13"
quinn = "~0.7.2"
serde = { version = "~1.0.128", features=["derive"] }
serde_json = "~1.0.66"
thiserror = "1.0.29"
tracing = "~0.1.27"
tracing-futures = "~0.2.5"
tracing-subscriber = "~0.2.22"
tokio = { version = "^1.11.0", features=["net", "io-util", "signal", "sync", "time", "macros", "rt-multi-thread"] }
tokio-stream = { version = "^0.1.7", features=["net", "io-util", "sync"] }
tokio-util = { version = "^0.6.8", features=["default", "io", "time"] }

[lib]
crate-type = ["rlib", "cdylib"]

[features]
default = ["core"]
core = []

full = ["core"]
